version: "3"
services:
  main:
    build:
      context: ./
      args:
        GID: 5032
        UID: 5032
        USER_NAME: kazuma_nis
    container_name: fastrusco
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              count: all
    image: fastrusco
    shm_size: 10.24gb
    tty: True
    volumes:
      - type: bind
        source: ./
        target: /app/
 