version: "3"
services:
  fastrusco-service:
    build:
      context: ./
      args:
        GID: 5032
        UID: 5032
        USER_NAME: kazuma_nis
    container_name: fastrusco-container
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              count: all
    volumes:
      - type: bind
        source: ./
        target: /workspace/
    shm_size: 10.24gb
    tty: True
